FROM node:20-alpine

RUN mkdir /src

COPY ./src/muzak /src

COPY ./src/muzak/albums.js /src
COPY ./index.muzak.js /src

COPY ./package.json /src
COPY ./package-lock.json /src

RUN chown node -R /src

WORKDIR /src

EXPOSE 3001

RUN npm ci --omit=dev

CMD [ "npm", "run", "start:muzak" ]